### ISSUE TITLE
2017 update ?

### ISSUE THREAD

**Issue by cp-richard** [davidschwegler/lfnw#7]
What is needed for 2017 updates ?

**Comment by davidschwegler** [comment]
@kti-richard I don't have time to update this myself this year. When Iast checked LFNW had broken the sign-in endpoints, so I couldn't get into the app to test other stuff. I recall there also being some issues last year related to events later in the day having incorrect times, so that would need to be looked at.

I'm happy to give advice if you or someone else wants to take it on!

**Comment by davidschwegler** [comment]
@kti-richard I've updated it for 2017. Let me know if you have issues.
